### PR TITLE
feat: Invalidate nonce

### LINKED ISSUE #4: Invalidate nonce
Owner should be able to invalidate [nonce](https://github.com/ubiquity/nft-rewards/blob/31871eb28c84fe0b95b413e2ea420c8c52191255/src/NftReward.sol#L23) for already signed mint request.

What should be done:
1. Add a new method `invalidateNonce()` where owner can pass a nonce value and invalidate mint request.
2. Cover with tests the `invalidateNonce()` method

### PR DESCRIPTION
**Pull request by gpylypchuk**
Resolves #4 issue.

### CODE REVIEW

**Review by rndquu — APPROVED** [review]

**Comment by molecula451** [comment]
looking good but it left to desire a bit, @gpylypchuk can you add a `require()` statement that checks the nonce has not been used?

**Review by molecula451 — CHANGES_REQUESTED** [review]
looking good but it left to desire a bit, @gpylypchuk can you add a `require()` statement that checks the nonce has not been used?

**Comment by gpylypchuk** [comment]
> looking good but it left to desire a bit, @gpylypchuk can you add a `require()` statement that checks the nonce has not been used?

sure! added :)

**Review by molecula451 — APPROVED** [review]
I'm accepting this PR because:

1. rndquu already put eyes on it
2. the PR meet the specification and conversational at the PR issue
3. the user applied all the changes and meet the specification
4. I tested locally and it invalidate the stuff

Last but not least:

1. There might be other edges cases to improve the security of the invalidation

**Pull request merged**
